### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Jaladhjin** [portapps/twitch-portable#2]
Do you think this will ever be updated to allow Twitch to update as it wants to ?

Or is that not possible since Twitch will want to write to the local machine ?

The reason I ask is I have a portable app USB with a Discord Portable on it.. & that I update right through Discord as though it was an installed app..

The only changes to my portable app folder for Discord are: https://i.imgur.com/5hbXP1e.png

If such a thing is not & will likely not ever be a thing for this Twitch is it recommended to just disable Twitch checking for updates then & plan to use your .exe updater ?

I noticed the updater method was recommended on the front page.. what happens when you run the installer to update do you just point it at your currently installed directory & it updates real classy like ?

Or is it one of those you must 1st uninstall the old build all but your settings.. reinstall..

**Comment by crazy-max** [comment]
Hi @Jaladhjin !

Compared to Discord or other "standard" Electron-based applications, Twitch installs itself in a circuitous way. When it updates itself automatically, it does not write to the local machine. That's why it is not necessary to download the latest twitch-portable setup every time.

However, for Discord and other Portapps applications that use the Squirrel update process with Electron, you must use the setup provided by portapps. In the latest versions I've released, automatic updates are disabled to avoid the problem you've encountered.

Seeing your screenshot I realize that you are not using the last setup provided for Discord. Today, the file structure looks like this:

![image](https://user-images.githubusercontent.com/1951866/36746532-d8650d30-1bf2-11e8-8ffd-2c11fe8a49c2.png)

I suggest to move everything in `data\AppData\Roaming\discord\*` to `data` folder and remove folder `data\AppData` and then remove everything in the root folder except `data` and install the latest setup : https://github.com/portapps/discord-portable/releases/download/0.0.300-22/discord-portable-win32-0.0.300-22-setup.exe

Then compared to the setup proposed by portapps, this one will delete everything except the data folder and install the latest update. So there's no need for manual operations on your part.

With your questions I think i will set up a FAQ ;)

Thanks for your input!

**Comment by Jaladhjin** [comment]
So a proper portable install would mean there were no files in the local machine %appdata ?

I think that's accurate & if so I kinda get that part..

And by updating apps like the Discord Portable through the application itself.. it then writes to the local machine ?

So why after a new Windows 10 install did my USB app still seem to work ?

Versus It seemed like with Twitch when the app itself updated.. then it moved the install to the local machine that was what I was originally thinking anyway..
